AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - db/schema.rb
    - spec/dummy/**/*

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*.rb
    - lib/**/*.rake

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineIfModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/RescueStandardError:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
